Use customerdatabase;
SELECT * FROM Customers;
SELECT * FROM products;
SELECT * FROM OrderDetails;
SELECT * FROM Orders;
SELECT * FROM Orders,Customers;
SELECT * FROM products,Orders Order by OrderID;
SELECT Customers.* FROM Customers,Orders GROUP BY CustomerID;
SELECT Customers.* FROM Customers JOIN Orders ON Orders.CustomerID = Customers.CustomerID GROUP BY CustomerID HAVING COUNT(OrderID)>1;
SELECT * FROM products WHERE UnitPrice>1000;
SELECT SUM(TotalAmount) as 'Total Sale' FROM Orders;
SELECT Customers.*, COUNT(OrderID) as 'Order Count'  FROM Customers JOIN Orders ON Customers.CustomerID = Orders.CustomerID  GROUP BY CustomerID;
SELECT Max(UnitPrice) AS "Most Expensive Product" FROM Products;
SELECT Min(UnitPrice) AS "Cheapest Product" FROM Products;
SELECT avg(TotalAmount) AS "Average" FROM Orders;
SELECT concat(FirstName," ",LastName), SUM(TotalAmount) AS "Total Amount", Max(TotalAmount) as "Most Expensive" FROM Customers JOIN Orders ON Customers.CustomerID = Orders.CustomerID Group By concat(FirstName," ",LastName);
SELECT * FROM Customers WHERE City="Durban";
SELECT avg(UnitPrice) AS Average FROM Products;
SELECT SUM(StockQuantity) AS "Total Quantity of Items" FROM Products;